### ISSUE TITLE
Want to join forces?

### ISSUE THREAD

**Issue by SaadiSave** [podusowski/rhorizons#8]
I have committed the initial API to [my repository](https://github.com/SaadiSave/horizons-rs). Please have a look and let me know if you want to join forces.

**Comment by podusowski** [comment]
That's quite a lot of code you have there, shame you haven't push that earlier. I wouldn't start writing my own. :) And it seems there are quite substantial differences so maybe let's just keep a close eye on each others repos and maybe some day they will become similar enough to try merging. Does it sound reasonable?

**Comment by SaadiSave** [comment]
We can still merge, I've only been working on the request portion of the API. It seems that you've done most of your work on parsing and presenting the response. Merging ought to be easy.

**Comment by podusowski** [comment]
> It seems that you've done most of your work on parsing and presenting the response.

Just the ephemeris and ids of the bodies and it still needs some polishing around error handling since it `unwrap`s a lot. My goal was to implement minimal set of features allowing someone to write newtonian simulator of the system. So just the vectors, masses and names with hard-coded units and reference point.

> but wasn't really motivated to finish and polish it

Yeah, JPL does know how to demotivate someone to use their API :)

> I can already see how we could integrate 95% of your code without any changes.

Cool. Let me know how'd you like to do it.

**Comment by SaadiSave** [comment]
Okay, I will elaborate my plans tomorrow, because it's midnight in India right now.

**Comment by SaadiSave** [comment]
Firstly, most of the parsing code can be moved immediately. The module tree would be split into two main areas, `request` and `response`. The code from `ephemeris.rs` and `utilities.rs` can be moved into the response module right now (if you consent to it). `client.rs` would require some modification to use the api provided by `request`, but it can otherwise be moved to `request`.

Here's how the tree would look:
```
src/
├─ lib.rs
├─ request/
│  ├─ presets.rs (client.rs)
│  ├─ .../
├─ response/
│  ├─ utilities.rs
│  ├─ ephemeris.rs
│  ├─ .../
```

If I have your consent, I shall open a commit the code from those files into my repo with your name under the commit authors list.

**Comment by podusowski** [comment]
Of course, please go ahead.

**Comment by SaadiSave** [comment]
If csv output is available, shouldn't we be parsing in csv format instead of text?

**Comment by podusowski** [comment]
It would simplify a lot, but I didn't know it's even available.

You can select a JSON in the API, but it's just the same text wrapped in an object. :)

**Comment by podusowski** [comment]
Parser more or less works, therefore I would rather leave it for later as a totally different task. CI and MVP should have the priority before under-the-hood changes. To be honest, some roadmap would be nice for this lib too. Working in the team has some boilerplate unfortunately.

**Comment by SaadiSave** [comment]
In my opinion, the MVP should only include state vectors for now. Parsing could be as simple as detecting `$$SOE$$` and `$$EOE$$` and deserialising everything between them using the CSV crate.

I also think that we should choose an HTTP client for the library user, but take inspiration from tower's `Service` trait. But we can do that after MVP.

Let me know what you think.

**Comment by podusowski** [comment]
I don't know. I mean, usually I do appreciate ability to inject or swap stuff, but over the years I've also started to appreciate things that just work without questions asked. I'd rather imagine that users of this library would be some scientists or something, who might not want to care about choosing a HTTP library.

I've been thinking a lot before writing [this kind of tests](https://github.com/podusowski/rhorizons/blob/main/tests/real_horizons.rs). They don't mock out the client, nor set up a fake server, instead they talk to the real thing. Sure, they will brake when API changes or won't work at all if someone doesn't have Internet access or is behind some proxy (I don't know if `reqwest` can read the system config) etc. But ultimately I've concluded that benefits outweigh the risks. And they already payed off. It turned out that JPL's API fails a lot and retries are needed.

**Comment by SaadiSave** [comment]
Are you continuing development of this crate?

**Comment by podusowski** [comment]
Not as actively as before, but I will accept some PRs and make releases if something pops in.

**Comment by podusowski** [comment]
Just cleaning up old tickets.
